name: Update version and add release

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]


jobs:
  Update-Version-In-Pubspec:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bulwinkel/flutter-version-action@main
        name: Update version in pubspec.yaml
        with:
          pubspec_path: pubspec.yaml