name: Update version and add release

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]


jobs:
  Update-Version-In-Pubspec:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bulwinkel/flutter-version-action@main
        name: Update version in pubspec.yaml
        id: version_bot
        with:
          pubspec_path: pubspec.yaml

      - name: Add & Commit Version
        uses: EndBug/add-and-commit@v8.0.1
        with:
          author_name: Version Bot
          message: Update version to ${{ steps.version_bot.new_version }}+${{ steps.version_bot.new_build }}