name: Update version and add release

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]

jobs:
  Update-Version-In-Pubspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update version in pubspec.yaml
        uses: bulwinkel/flutter-version-action@main
        id: version_bot
        with:
          pubspec_path: pubspec.yaml

      - name: Add & Commit Version
        uses: EndBug/add-and-commit@v8.0.1
        id: commit_bot
        with:
          author_name: Version Bot
          message: Update version to ${{ steps.version_bot.outputs.new_version }}+${{ steps.version_bot.outputs.new_build }}
          push: true

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

    outputs:
      commit_hash: ${{ steps.commit_bot.outputs.commit_long_sha }}
      new_version: ${{ steps.version_bot.outputs.new_version }}

  Create-Release:
    runs-on: ubuntu-latest
    needs:
      - Update-Version-In-Pubspec
    steps:
      - name: Create releaes
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ needs.Update-Version-In-Pubspec.outputs.new_version }}
          prerelease: true